-- Project: Los Santos Online Roleplay (LSORP)
-- Author: Gerrit S. | Gerrxt (Admin of LSORP)
-- Last Date: 01.12.2023 (Created the file on 01.12.2023)
-- Version: 1.0.0 (Current version)
-- Official Documentation:
-- Official Discord:
-- Script Side: Client